[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vapm_decisions = "6xDo2r8Edvu1MHxwUtqmmzm3Auavf2fokbjGoJHxcMLx"

[programs.devnet]
vapm_decisions = "6xDo2r8Edvu1MHxwUtqmmzm3Auavf2fokbjGoJHxcMLx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
